[package]
name = "twitt_rss"
version = "0.1.0"
authors = ["Martin Hartl <martin@hartl.co>"]
edition = "2018"

[dependencies]
egg-mode = "0.15.0"
rss = "1.0"
config = "0.9.2"
actix-web = { version = "3", features = ["openssl"] }