[package]
name = "twitt_rss"
version = "0.1.0"
authors = ["Martin Hartl <martin@hartl.co>"]
edition = "2018"

[dependencies]
egg-mode = "0.13.0"
tokio-core = "0.1"
rss = "1.0"
rouille = "3.0.0"
config = "0.9.2"