port = "6060"

# Values from Twitter App
consumer_key = "XXX"
consumer_secret = "XXX"
access_token = "XXX"
access_token_secret = "XXX"

# Username and name of the list to convert into RSS
username = "twitter-username"
listname = "twiter-list-name"

# Config for the actual RSS stream
rss_title = "Twitter"
rss_url = "https://twitter.com"
rss_description = "RSS stream for Twitter list"
